//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Visual Studio settings designer.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweakHub.Properties;

[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
{
    private static readonly Settings defaultInstance =
        (Settings)Synchronized(new Settings());

    public static Settings Default => defaultInstance;

    [global::System.Configuration.UserScopedSetting]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Configuration.DefaultSettingValue("System")]
    public string Theme
    {
        get => (string)this[nameof(Theme)];
        set => this[nameof(Theme)] = value;
    }

    [global::System.Configuration.UserScopedSetting]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Configuration.DefaultSettingValue("")]
    public string AccentColor
    {
        get => (string)this[nameof(AccentColor)];
        set => this[nameof(AccentColor)] = value;
    }

    [global::System.Configuration.UserScopedSetting]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Configuration.DefaultSettingValue("True")]
    public bool Transparency
    {
        get => (bool)this[nameof(Transparency)];
        set => this[nameof(Transparency)] = value;
    }

    [global::System.Configuration.UserScopedSetting]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Configuration.DefaultSettingValue("False")]
    public bool AppearanceConfigured
    {
        get => (bool)this[nameof(AppearanceConfigured)];
        set => this[nameof(AppearanceConfigured)] = value;
    }
}
